// Code generated by Slice Machine. DO NOT EDIT.

import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';
import Youtube from './Youtube';

export {
	ContactForm,
	Image,
	Quote,
	Text,
	Youtube,
};

export const components = {
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	text: Text,
	youtube: Youtube,
};
